name: InventorySync
version: ${project.version}
main: net.gigaclub.inventorysync.Main
api-version: 1.13
authors: [KevTVKevin]
description: Plugin, welches das Inventar mehrerer Server synchronisieren kann.
website: https://GigaClub.net
